import yargs from "yargs";
import { hideBin } from "yargs/helpers";
import { configure as configureLogging } from "./logger";
import { run as stackReport } from "./stack-report";

configureLogging();

void yargs(hideBin(process.argv))
  .command("overview", "list stacks, contained resources, and if generated by @guardian/cdk", () => {
    stackReport()
      .then(() => console.log("Done"))
      .catch((err) => {
        console.error(err);
        process.exit(1);
      });
  })
  .option("prefer-cache", {
    type: "boolean",
    description: "use local cache and fail is not found",
  })
  .parse();
